#!/bin/sh
[ -f "/etc/config/turboacc" ] && exit 0

touch /etc/config/turboacc
uci batch <<EOF
	set turboacc.config=turboacc
	set turboacc.config.sw_flow='1'
	set turboacc.config.hw_flow='0'
	set turboacc.config.bbr='1'
	set turboacc.config.fullcone='1'
	commit turboacc
EOF
exit 0
